# Generated by Django 4.0.3 on 2022-10-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_baslik', models.CharField(max_length=200)),
                ('baslik', models.CharField(max_length=200)),
                ('tarih', models.CharField(max_length=50)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('yazi1', models.TextField(max_length=5000)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('yazı2', models.TextField(max_length=5000)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('yaziBenzersizId', models.CharField(max_length=10)),
            ],
        ),
    ]
