# Generated by Django 4.0.3 on 2022-10-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_yazilar_yazi_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilar',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='yazilar',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='yazilar',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
