# Generated by Django 4.1.2 on 2022-10-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_yazilar_img1_alter_yazilar_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilar',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yazilar',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yazilar',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
